[toolchain]
# Be sure to update the 'rust-overlay' module's url in shell.nix to point to a
# commit which supports the required rustc version and also update the version
# in support/crown/rust-toolchain.toml when bumping this!
channel = "1.89.0"

components = [
    "clippy",
    # For support/crown linter
    "llvm-tools",
    "rustc-dev",
    "rustfmt",
    # For rust-analyzer
    "rust-src",
]
